// <auto-generated />
using EFC_02_QuanLyCongThucNauAn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC_02_QuanLyCongThucNauAn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230703040018_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.CongThuc", b =>
                {
                    b.Property<int>("CongThucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongThucId"));

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonAnId")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("CongThucId");

                    b.HasIndex("MonAnId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("CongThuc");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.LoaiMonAn", b =>
                {
                    b.Property<int>("LoaiMonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiMonAnId"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoaiMonAnId");

                    b.ToTable("LoaiMonAn");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.MonAn", b =>
                {
                    b.Property<int>("MonAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonAnId"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiMonAnId")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonAnId");

                    b.HasIndex("LoaiMonAnId");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuId"));

                    b.Property<string>("TenNguyenLieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguyenLieuId");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.CongThuc", b =>
                {
                    b.HasOne("EFC_02_QuanLyCongThucNauAn.Models.MonAn", "MonAn")
                        .WithMany("ListCongThuc")
                        .HasForeignKey("MonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFC_02_QuanLyCongThucNauAn.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("ListCongThuc")
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.MonAn", b =>
                {
                    b.HasOne("EFC_02_QuanLyCongThucNauAn.Models.LoaiMonAn", "LoaiMonAn")
                        .WithMany("ListMonAn")
                        .HasForeignKey("LoaiMonAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMonAn");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.LoaiMonAn", b =>
                {
                    b.Navigation("ListMonAn");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.MonAn", b =>
                {
                    b.Navigation("ListCongThuc");
                });

            modelBuilder.Entity("EFC_02_QuanLyCongThucNauAn.Models.NguyenLieu", b =>
                {
                    b.Navigation("ListCongThuc");
                });
#pragma warning restore 612, 618
        }
    }
}
