//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC_02_QuanLyCongThucNauAn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CongThucNauAnRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CongThucNauAnRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFC_02_QuanLyCongThucNauAn.Resources.CongThucNauAnRes", typeof(CongThucNauAnRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap don vi tinh: .
        /// </summary>
        internal static string DonViTinh {
            get {
                return ResourceManager.GetString("DonViTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap loai mon an ID la so!.
        /// </summary>
        internal static string ErrorLoaiMonAnId {
            get {
                return ResourceManager.GetString("ErrorLoaiMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap mon an ID la so!.
        /// </summary>
        internal static string ErrorMonAnId {
            get {
                return ResourceManager.GetString("ErrorMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap nguyen lieu ID la so!.
        /// </summary>
        internal static string ErrorNguyenLieuId {
            get {
                return ResourceManager.GetString("ErrorNguyenLieuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui long nhap vao so!.
        /// </summary>
        internal static string ErrorSoLuong {
            get {
                return ResourceManager.GetString("ErrorSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ghi chu: .
        /// </summary>
        internal static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap loai mon an ID: .
        /// </summary>
        internal static string LoaiMonAnId {
            get {
                return ResourceManager.GetString("LoaiMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sach trong!.
        /// </summary>
        internal static string LogDanhSachTrong {
            get {
                return ResourceManager.GetString("LogDanhSachTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay mon an!.
        /// </summary>
        internal static string LogKhongTimThayMonAn {
            get {
                return ResourceManager.GetString("LogKhongTimThayMonAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh cong!.
        /// </summary>
        internal static string LogThanhCong {
            get {
                return ResourceManager.GetString("LogThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap mon an ID: .
        /// </summary>
        internal static string MonAnId {
            get {
                return ResourceManager.GetString("MonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap nguyen lieu ID: .
        /// </summary>
        internal static string NguyenLieuId {
            get {
                return ResourceManager.GetString("NguyenLieuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so luong: .
        /// </summary>
        internal static string SoLuong {
            get {
                return ResourceManager.GetString("SoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten loai: .
        /// </summary>
        internal static string TenLoai {
            get {
                return ResourceManager.GetString("TenLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten mon: .
        /// </summary>
        internal static string TenMon {
            get {
                return ResourceManager.GetString("TenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten nguyen lieu: .
        /// </summary>
        internal static string TenNguyenLieu {
            get {
                return ResourceManager.GetString("TenNguyenLieu", resourceCulture);
            }
        }
    }
}
